name: Task 5

on:
  workflow_dispatch:

jobs:
  cache-restore-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Restore NPM cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Cache hit print
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "Cache hit!"
      - name: Install dependencies
        run: npm ci