name: Task 2

on:
  workflow_dispatch:

jobs:
  matrix-failfast:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Print OS
        run: echo "Running on OS = ${{ matrix.os }}"

      - name: Fail on Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: exit 1