name: Task 6

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    outputs:
      NODE_USED:
        value: ${{ jobs.install.outputs.NODE_USED }}

jobs:
  install:
    runs-on: ubuntu-latest

    outputs:
      NODE_USED: ${{ steps.node_version.outputs.NODE_USED }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: node output
        id: node_version
        run: echo "NODE_USED=${{ inputs.node-version }}" >> $GITHUB_OUTPUT
