name: Task 1

on:
  workflow_dispatch:

jobs:
  matrix-demo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Node Version
        run: echo "Running on Node version = ${{ matrix.node-version }}"