name: Task 10

on:
  workflow_dispatch:

jobs:
  use-reusable-workflow:
    uses: ./.github/workflows/task6.yml
    with:
      node-version: '16'

  print:
    runs-on: ubuntu-latest
    needs: use-reusable-workflow
    
    steps:
      - name: Print Output
        run: echo "Node used = ${{ needs.use-reusable-workflow.outputs.NODE_USED }}"

# name: Task 6

# on:
#   workflow_call:
#     inputs:
#       node-version:
#         required: true
#         type: string
#     outputs:
#       NODE_USED: 
#         value: ${{ jobs.install.outputs.NODE_USED }}
# jobs:
#   install:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout repo
#         uses: actions/checkout@v4
#       - name: use node version
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ inputs.node-version }}
#       - name: node output
#         id: node_version
#         run: echo "NODE_USED=${{  inputs.node-version }}" >> $GITHUB_OUTPUT
#       - name: install dependencies
#         run: npm ci        