name: Task 13

on:
  workflow_dispatch:

jobs:
  job-status-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Succeed"
      - name: test
        run: echo "exit 1"
      - name: On-success
        if: success()
        run: echo "On-Success"
      - name: on-failure
        if: failure()
        run: echo "On-failure"
      - name: always-run
        if: always()
        run: echo "Always Run"